---
- hosts: loadbalancer
  sudo: yes

  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes
    
    - name: Status of the nginx server on loadbalancer must be started
      service: name=nginx state=started enabled=yes
