---
- hosts: loadbalancer
  become: true

  tasks:
    - name: Install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-httplib2

    - name: install nginx
      apt: name=nginx state=present update_cache=yes
    
    - name: Status of the nginx server on loadbalancer must be started
      service: name=nginx state=started enabled=yes

    - name: configure nginx site
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
      notify: restart nginx

    - name: de-activate default nginx website
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx

    - name: Activate demo nginx sites-enabled
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx 

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
