---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: Check the status of nginx
        command: service nginx status

      - name: Check the Port connectivity for nginx at port 80
        wait_for: port=80 timeout=5


  - hosts: webserver
    become: true
    tasks:
      - name: Check the status of Apache
        command: service apache2 status

      - name: Check the Port connectivity for Apache2 at port 80
        wait_for: port=80 timeout=5


  - hosts: database
    become: true
    tasks:
      - name: Check the status of mysql DB at port 3306
        command: service mysql status 

      - name: Check the Port connectivity for mysql 3306
        wait_for: port=3306 timeout=5
