---
  - hosts: webserver
    become: true
    tasks:
      - name: Installaing webserver packages on the web hosts
        apt: name={{item}} state=absent update_cache=yes
        with_items: 
           - apache2
           - libapache2-mod-wsgi
           - python-pip
           - python-virtualenv
