---
  - hosts: webserver
    become: true
    tasks:
      - name: Installaing webserver packages on the web hosts
        apt: name={{item}} state=present update_cache=yes
        with_items: 
           - apache2
           - libapache2-mod-wsgi
           - python-pip
           - python-virtualenv
      - name: ensure Apache is started
        service: name=apache2 state=started enabled=yes
      - name: ensure mod_wsgi enabled
        apache2_module: state=present name=wsgi
        notify: restart apache2

    handlers:
      - name: Restart Apache2
        service: name=apache2 state=restarted
